const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const records=new Map();let fail=false;
function context(site){
 const nodes=new Map(['save-status','save-workspace','project','title','date','photos-per-page','photos-input'].map(k=>[k,{value:'',dataset:{},click(){this.clicked=true}}]));
 const document={querySelector:s=>nodes.get(s.slice(1)),getElementById:s=>nodes.get(s),addEventListener(){}};
 const indexedDB={open(){const r={};setImmediate(()=>{const db={close(){},transaction(name,mode){const tx={objectStore(){return{get(key){const req={result:records.get(key)&&structuredClone(records.get(key))};setImmediate(()=>tx.oncomplete());return req},put(value){const req={};setImmediate(()=>{if(fail){tx.error=Error('quota');tx.onabort()}else{records.set(value.id,structuredClone(value));tx.oncomplete()}});return req}}}};return tx}};r.result=db;r.onsuccess()});return r}};
 const c={console:{error(){}},structuredClone,Promise,URLSearchParams,Date,WeakMap,Image:class{async decode(){}},indexedDB,document,window:{addEventListener(){}},location:{search:'?projectId='+site+'&projectName='+site},setTimeout,clearTimeout};vm.createContext(c);
 vm.runInContext(fs.readFileSync(path.join(__dirname,'../snapshot/workspace.js'),'utf8').replace('export function','function'),c);
 return {c,nodes,run:s=>vm.runInContext(s,c)};
}
(async()=>{
 const a=context('A');a.run(`state={photos:[],drawings:[],paperSize:'A3',orientation:'portrait',photosPerPage:8,pageCounts:{'A3-portrait':8},view:'photos'}; api=setupSavedWorkspace({state,meta:()=>({title:'指示書',project:'A',date:'2026-10-09'}),render(){},switchView(){},setPaperLayout(){},addPhotos:async files=>{state.photos.push(...files)},toast(){}})`);await a.run('api.ready');
 a.run(`state.photos=[{id:'p1',src:'original',img:{},editedCanvas:{},originalImage:{},editedSrc:'edited',rotation:1,comment:'確認',annotations:[{id:'note',type:'text',text:'修正'}],sourcePhotoId:'source1',w:200,h:300}];state.drawings=[{id:'d1',w:300,h:200,canvas:{toDataURL:()=> 'drawing-base'},annotations:[{photoId:'p1',type:'number'}],history:[[]],hi:0}];`);await a.run('api.flush()');
 const saved=records.get('project:A');assert.equal(saved.photos[0].comment,'確認');assert.equal(saved.photos[0].sourcePhotoId,'source1');assert(!('img'in saved.photos[0]));assert(!('canvas'in saved.drawings[0]));assert.equal(saved.drawings[0].base,'drawing-base');
 fail=true;a.run(`state.photos[0].comment='未保存'`);await assert.rejects(a.run('api.flush()'),/保存できません/);assert.equal(records.get('project:A').photos[0].comment,'確認');assert.match(a.nodes.get('save-status').textContent,/保存できません/);fail=false;await a.run('api.flush()');assert.equal(records.get('project:A').photos[0].comment,'未保存');
 const b=context('B');b.run(`state={photos:[],drawings:[],paperSize:'A4',orientation:'landscape',pageCounts:{},view:'photos'};api=setupSavedWorkspace({state,meta:()=>({project:'B'}),render(){},switchView(){},setPaperLayout(){},addPhotos:async files=>state.photos.push(...files),toast(){}})`);await b.run('api.ready');assert.equal(b.run('state.photos.length'),0);await b.run(`api.importPhotos([{id:'b1',src:'direct'}])`);assert.equal(records.get('project:B').photos[0].id,'b1');assert.equal(records.get('project:A').photos[0].id,'p1');
 const re=context('A');re.c.document.createElement=()=>({getContext:()=>({drawImage(){}})});re.run(`state={photos:[],drawings:[]};api=setupSavedWorkspace({state,meta:()=>({project:'A'}),render(){},switchView(){},setPaperLayout(){},addPhotos:async()=>{},toast(){}})`);await re.run('api.ready');assert.equal(re.run('state.photos[0].comment'),'未保存');assert.equal(re.run('state.photos[0].rotation'),1);assert.equal(re.run('state.photos[0].annotations[0].text'),'修正');assert.equal(re.run('state.drawings[0].annotations[0].photoId'),'p1');assert.equal(re.run('state.photosPerPage'),8);assert.equal(re.run('state.paperSize'),'A3');
 const parent={data:{projects:[{id:'A'}],photos:[{id:'a',projectId:'A',folderId:'one'},{id:'child',projectId:'A',folderId:'sub'},{id:'other',projectId:'A',folderId:'two'},{id:'foreign',projectId:'B',folderId:'one'},{id:'none',projectId:'A'}]},projectId:'A',page:'snapshot',document:{addEventListener(){}}};parent.items=k=>parent.data[k].filter(x=>x.projectId==='A');parent.isInFolder=(f,s)=>f===s||(f==='sub'&&s==='one');vm.createContext(parent);vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/snapshot.js'),'utf8'),parent);const run=s=>vm.runInContext(s,parent);run(`snapshotPickerFolder='one'`);assert.deepEqual(Array.from(run('snapshotFolderPhotos().map(p=>p.id)')),['a','child']);run(`snapshotPickerFolder='none'`);assert.deepEqual(Array.from(run('snapshotFolderPhotos().map(p=>p.id)')),['none']);
 console.log('PASS: project-scoped saved workspaces, annotations/number links, edited originals, paper settings, reload, quota failure/retry, direct import, exact source isolation and nested photo-folder filtering');
})().catch(e=>{console.error(e);process.exitCode=1});
